import turtle
t = turtle . Pen ()
#body
t . left (30)
t . forward (100)
t . left (90)
t . forward (150)
t . left (90)
t . forward (100)
t . left(90)
t . forward (150)
t . left (90)
#thigh
t . up ()
t . forward (25)
t . down ()
t . right (126)
t . forward (75)
t . left (40)
#culf
t . forward (75)
t . right (90)
t . forward (37)
t . left (90)
t . forward (25)
t . left (90)
#shoe
for i in range(3):
    t . forward (8)
    t . right (90)
    t . forward (8)
    t . right (180)
    t . up ()
    t . forward (8)
    t . right (90)
    t . down()
t . forward (13)
t . left (90)
t . forward (25)
t . up ()
t . forward (75)
t . right (40)
t . forward (75)
#gap between legs
t . right (54)
t . forward (50)
t . down ()
#second thigh
t . right (126)
t . forward (75)
t . left (80)
#second calf
t . forward (75)
t . left (50)
t . forward (25)
t . right (90)
#second shoe
for i in range(3):
    t . forward (8)
    t . left (90)
    t . forward (8)
    t . left (180)
    t . up()
    t . forward (8)
    t . down ()
    t . left (90)
t . forward (8)
t . right (90)
t . forward (25)
t . right (90)
t . forward (32)
t . right (90)
t . up()
#Ball
t . forward (60)
t . down ()
t . right (90)
t . circle (30)
#Back to the body
t . up()
t . right (90)
t . forward (60)
t . right (50)
t . forward (75)
t . right (80)
t . forward (75)
t . right (54)
t . forward (25)
t . left (90)
t . forward (150)
#Hand
t . right (125)
t . down ()
t . forward (80)
t . right (80)
t . forward (110)
t . right (90)
t . circle (10)
t . right (90)
t . up ()
t . forward (110)
t . left (80)
t . forward (80)
#Head
t . left (35)
t . forward (50)
t . right (90)
t . forward (15)
t . right (90)
t . down()
t . circle (30)
#Eye 1
t . left (90)
t . up ()
t . forward (35)
t . down ()
t . right (90)
t . circle (5)
#Eye 2
t . up ()
t . forward (15)
t . down ()
t . circle (5)
#Hand 2
t . right (90)
t . up ()
t . forward (50)
t . right (90)
t . forward (65)
t . left (35)
t . down()
t . forward (80)
t . left (20)
t . forward (110)
t . right (90)
t . circle (10)
